# Generated by Django 6.0.6 on 2026-07-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='badge',
            field=models.CharField(choices=[('new', 'New'), ('discounted', 'Discounted')], default='new', max_length=100),
        ),
    ]
