# Generated by Django 6.0.6 on 2026-08-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_remove_category_image_category_css_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='css_class',
            field=models.CharField(default='', max_length=100),
        ),
    ]
