from decimal import Decimal

from django.core.management.base import BaseCommand

from product_app.models import Brand, Category, Product, ProductBadge, ProductDescription

NEW_PRODUCTS = [
    {'name': 'Zinc Immune Tablets', 'brand': 'VitaLife', 'category': 'Health care', 'short_description': 'Daily zinc support for immunity', 'description': 'High-absorption zinc tablets to support immune function and wound healing.', 'price': Decimal('16.00'), 'stock': 45, 'badge': 'new', 'descriptions': ['15mg elemental zinc per tablet.', 'Supports immune system function.', 'Take one tablet daily.', 'Suitable for adults.']},
    {'name': 'Magnesium Glycinate', 'brand': 'HealthPlus', 'category': 'Health care', 'short_description': 'Relax muscles and improve sleep quality', 'description': 'Gentle magnesium glycinate formula for muscle relaxation and restful sleep.', 'price': Decimal('22.00'), 'stock': 38, 'badge': 'discounted', 'descriptions': ['Highly absorbable glycinate form.', 'Supports muscle and nerve function.', 'Take before bedtime.', '200mg per capsule.']},
    {'name': 'B-Complex Vitamins', 'brand': 'Perfectil', 'category': 'Health care', 'short_description': 'Energy support B vitamin blend', 'description': 'Complete B-complex for energy metabolism and nervous system support.', 'price': Decimal('18.00'), 'stock': 52, 'badge': 'new', 'descriptions': ['All eight essential B vitamins.', 'Supports energy production.', 'One capsule with breakfast.', 'Vegetarian friendly.']},
    {'name': 'Turmeric Curcumin', 'brand': 'VitaLife', 'category': 'Health care', 'short_description': 'Joint comfort and antioxidant support', 'description': 'Standardized curcumin extract with black pepper for enhanced absorption.', 'price': Decimal('24.00'), 'stock': 41, 'badge': 'discounted', 'descriptions': ['95% curcuminoid extract.', 'Added piperine for absorption.', 'Supports joint comfort.', 'Take with meals.']},
    {'name': 'CoQ10 Softgels', 'brand': 'HealthPlus', 'category': 'Health care', 'short_description': 'Heart health and cellular energy', 'description': 'Coenzyme Q10 softgels for cardiovascular and cellular energy support.', 'price': Decimal('29.00'), 'stock': 33, 'badge': None, 'descriptions': ['100mg CoQ10 per softgel.', 'Supports heart health.', 'Take with fatty meal.', 'Ubiquinone form.']},
    {'name': 'Ashwagandha Capsules', 'brand': 'Perfectil', 'category': 'Health care', 'short_description': 'Stress relief and calm focus', 'description': 'Adaptogenic ashwagandha root extract for stress management and balance.', 'price': Decimal('21.00'), 'stock': 47, 'badge': 'new', 'descriptions': ['KSM-66 ashwagandha extract.', 'Helps manage daily stress.', 'Take one capsule twice daily.', 'Non-GMO formula.']},
    {'name': 'Calcium + Vitamin D', 'brand': 'MediCare', 'category': 'Health care', 'short_description': 'Bone strength daily supplement', 'description': 'Calcium carbonate with vitamin D3 for bone density and strength.', 'price': Decimal('15.00'), 'stock': 60, 'badge': 'discounted', 'descriptions': ['600mg calcium per serving.', 'Added vitamin D3 for absorption.', 'Supports bone health.', 'Two tablets daily.']},
    {'name': 'Elderberry Syrup', 'brand': 'VitaLife', 'category': 'Health care', 'short_description': 'Seasonal immune support syrup', 'description': 'Black elderberry syrup with vitamin C and zinc for immune support.', 'price': Decimal('19.00'), 'stock': 44, 'badge': 'new', 'descriptions': ['Rich in natural antioxidants.', 'Pleasant berry flavor.', 'Adults and children formula.', 'Use during cold season.']},
    {'name': 'Fiber Supplement Powder', 'brand': 'HealthPlus', 'category': 'Health care', 'short_description': 'Digestive regularity support', 'description': 'Soluble fiber powder that mixes easily to support digestive health.', 'price': Decimal('17.00'), 'stock': 36, 'badge': None, 'descriptions': ['5g fiber per scoop.', 'Unflavored and mixable.', 'Supports regular digestion.', 'Add to water or smoothies.']},
    {'name': 'Ginkgo Biloba Extract', 'brand': 'Perfectil', 'category': 'Health care', 'short_description': 'Memory and circulation support', 'description': 'Standardized ginkgo biloba extract for cognitive and circulatory support.', 'price': Decimal('20.00'), 'stock': 29, 'badge': 'discounted', 'descriptions': ['120mg standardized extract.', 'Supports mental clarity.', 'Take one capsule daily.', 'For adults only.']},
    {'name': 'Retinol Night Cream', 'brand': 'Perfectil', 'category': 'Beauty care', 'short_description': 'Anti-aging night moisturizer', 'description': 'Retinol night cream that smooths fine lines and renews skin overnight.', 'price': Decimal('34.00'), 'stock': 28, 'badge': 'new', 'descriptions': ['0.3% retinol formula.', 'Apply at night only.', 'Start with every other night.', 'Use SPF during the day.']},
    {'name': 'Vitamin C Serum', 'brand': 'VitaLife', 'category': 'Beauty care', 'short_description': 'Brightening antioxidant serum', 'description': '20% vitamin C serum for brighter, more even-toned skin.', 'price': Decimal('28.00'), 'stock': 35, 'badge': 'discounted', 'descriptions': ['Brightens dull complexion.', 'Fights free radical damage.', 'Apply before moisturizer.', 'Use in the morning.']},
    {'name': 'Charcoal Face Mask', 'brand': 'HealthPlus', 'category': 'Beauty care', 'short_description': 'Deep cleansing pore mask', 'description': 'Activated charcoal mask that draws out impurities and excess oil.', 'price': Decimal('14.00'), 'stock': 50, 'badge': 'new', 'descriptions': ['Deep cleans congested pores.', 'Use once or twice weekly.', 'Rinse after 10 minutes.', 'For oily and combination skin.']},
    {'name': 'Hyaluronic Acid Serum', 'brand': 'Perfectil', 'category': 'Beauty care', 'short_description': 'Intense hydration for all skin', 'description': 'Multi-weight hyaluronic acid serum for plump, hydrated skin.', 'price': Decimal('26.00'), 'stock': 42, 'badge': 'discounted', 'descriptions': ['Multi-molecular HA blend.', 'Plumps and hydrates skin.', 'Layer under moisturizer.', 'Suitable for all skin types.']},
    {'name': 'Argan Oil Hair Mask', 'brand': 'VitaLife', 'category': 'Beauty care', 'short_description': 'Repair dry damaged hair', 'description': 'Rich argan oil hair mask for deep conditioning and shine.', 'price': Decimal('18.00'), 'stock': 37, 'badge': None, 'descriptions': ['Moroccan argan oil formula.', 'Leave on for 5–10 minutes.', 'Restores shine and softness.', 'Use weekly.']},
    {'name': 'Niacinamide Toner', 'brand': 'HealthPlus', 'category': 'Beauty care', 'short_description': 'Pore-refining daily toner', 'description': '5% niacinamide toner that minimizes pores and balances skin tone.', 'price': Decimal('16.00'), 'stock': 48, 'badge': 'new', 'descriptions': ['Minimizes appearance of pores.', 'Balances uneven skin tone.', 'Apply after cleansing.', 'Alcohol-free formula.']},
    {'name': 'Shea Butter Body Lotion', 'brand': 'MediCare', 'category': 'Beauty care', 'short_description': 'Rich moisture for dry skin', 'description': 'Shea butter body lotion with vitamin E for all-day hydration.', 'price': Decimal('13.00'), 'stock': 55, 'badge': 'discounted', 'descriptions': ['24-hour moisture lock.', 'Non-greasy fast absorption.', 'For dry and sensitive skin.', 'Apply after shower.']},
    {'name': 'Biotin Shampoo', 'brand': 'Perfectil', 'category': 'Beauty care', 'short_description': 'Strengthen thinning hair', 'description': 'Biotin-enriched shampoo that strengthens hair and reduces breakage.', 'price': Decimal('15.00'), 'stock': 43, 'badge': 'new', 'descriptions': ['Biotin and keratin blend.', 'Strengthens weak strands.', 'Sulfate-free formula.', 'Use with matching conditioner.']},
    {'name': 'Aloe Vera Gel', 'brand': 'VitaLife', 'category': 'Beauty care', 'short_description': 'Soothing gel for skin relief', 'description': 'Pure aloe vera gel for sunburn, irritation, and dry skin relief.', 'price': Decimal('11.00'), 'stock': 62, 'badge': None, 'descriptions': ['99% pure aloe vera.', 'Soothes irritated skin.', 'Lightweight cooling gel.', 'Multi-purpose use.']},
    {'name': 'Exfoliating Scrub', 'brand': 'HealthPlus', 'category': 'Beauty care', 'short_description': 'Gentle weekly skin polish', 'description': 'Fine-grain exfoliating scrub that removes dead skin for a smooth glow.', 'price': Decimal('12.00'), 'stock': 40, 'badge': 'discounted', 'descriptions': ['Fine natural exfoliants.', 'Reveals smoother skin.', 'Use 1–2 times per week.', 'Rinse thoroughly after use.']},
    {'name': 'Pulse Oximeter', 'brand': 'MediCare', 'category': 'Medicine', 'short_description': 'Track blood oxygen at home', 'description': 'Fingertip pulse oximeter for SpO2 and heart rate monitoring.', 'price': Decimal('35.00'), 'stock': 30, 'badge': 'new', 'descriptions': ['SpO2 and pulse rate display.', 'Results in seconds.', 'Compact fingertip design.', 'Includes carrying case.']},
    {'name': 'Compression Bandages', 'brand': 'MediCare', 'category': 'Medicine', 'short_description': 'Elastic support for sprains', 'description': 'Self-adhesive compression bandages for sprains and strain support.', 'price': Decimal('9.00'), 'stock': 70, 'badge': 'discounted', 'descriptions': ['Self-adhesive elastic wrap.', 'Supports sprains and strains.', 'Breathable material.', 'Pack of two rolls.']},
    {'name': 'Hot Cold Pack', 'brand': 'HealthPlus', 'category': 'Medicine', 'short_description': 'Reusable therapy pack', 'description': 'Dual-purpose gel pack for hot or cold muscle and joint therapy.', 'price': Decimal('14.00'), 'stock': 45, 'badge': 'new', 'descriptions': ['Use hot or cold therapy.', 'Flexible gel conforms to body.', 'Reusable and durable.', 'Relieves muscle soreness.']},
    {'name': 'Nasal Saline Spray', 'brand': 'VitaLife', 'category': 'Medicine', 'short_description': 'Moisturize dry nasal passages', 'description': 'Isotonic saline nasal spray for congestion relief and moisture.', 'price': Decimal('8.00'), 'stock': 65, 'badge': None, 'descriptions': ['Isotonic saline formula.', 'Relieves nasal dryness.', 'Safe for daily use.', 'Drug-free relief.']},
    {'name': 'Antacid Tablets', 'brand': 'MediCare', 'category': 'Medicine', 'short_description': 'Fast heartburn relief', 'description': 'Chewable antacid tablets for quick relief from heartburn and indigestion.', 'price': Decimal('7.00'), 'stock': 80, 'badge': 'discounted', 'descriptions': ['Fast-acting chewable tablets.', 'Relieves heartburn quickly.', 'Pleasant mint flavor.', 'Take as needed.']},
    {'name': 'Lozenges Honey Lemon', 'brand': 'HealthPlus', 'category': 'Medicine', 'short_description': 'Soothe sore throat fast', 'description': 'Honey lemon lozenges that coat and soothe irritated throats.', 'price': Decimal('6.00'), 'stock': 90, 'badge': 'new', 'descriptions': ['Honey and lemon flavor.', 'Coats and soothes throat.', 'Relieves minor irritation.', 'Keep on hand during cold season.']},
    {'name': 'Wrist Support Brace', 'brand': 'MediCare', 'category': 'Medicine', 'short_description': 'Stabilize wrist during recovery', 'description': 'Adjustable wrist brace for sprain support and repetitive strain relief.', 'price': Decimal('19.00'), 'stock': 32, 'badge': 'discounted', 'descriptions': ['Adjustable Velcro straps.', 'Supports wrist joint.', 'Breathable neoprene.', 'Wear during activity.']},
    {'name': 'Insect Bite Cream', 'brand': 'VitaLife', 'category': 'Medicine', 'short_description': 'Relief from bites and stings', 'description': 'Topical cream that soothes itching and swelling from insect bites.', 'price': Decimal('10.00'), 'stock': 58, 'badge': None, 'descriptions': ['Soothes itch and swelling.', 'Apply to affected area.', 'Suitable for all ages.', 'Compact travel size.']},
    {'name': 'Medical Tape Roll', 'brand': 'MediCare', 'category': 'Medicine', 'short_description': 'Secure dressings in place', 'description': 'Hypoallergenic medical tape for securing gauze and bandages.', 'price': Decimal('5.00'), 'stock': 100, 'badge': 'new', 'descriptions': ['Hypoallergenic adhesive.', 'Tears easily by hand.', 'Securely holds dressings.', '10-meter roll.']},
    {'name': 'Steam Inhaler', 'brand': 'HealthPlus', 'category': 'Medicine', 'short_description': 'Relieve nasal congestion naturally', 'description': 'Personal steam inhaler for sinus relief and respiratory comfort.', 'price': Decimal('42.00'), 'stock': 22, 'badge': 'discounted', 'descriptions': ['Personal steam therapy device.', 'Relieves sinus congestion.', 'Easy to clean design.', 'Use with plain water.']},
    {'name': 'Kettlebell 8kg', 'brand': 'Perfectil', 'category': 'Fitness', 'short_description': 'Full-body strength training', 'description': 'Cast iron kettlebell for swings, squats, and functional training.', 'price': Decimal('38.00'), 'stock': 25, 'badge': 'new', 'descriptions': ['8kg cast iron kettlebell.', 'Wide handle for two-hand grip.', 'Flat base for storage.', 'Ideal for home workouts.']},
    {'name': 'Pull-Up Bar', 'brand': 'HealthPlus', 'category': 'Fitness', 'short_description': 'Doorway upper body trainer', 'description': 'Adjustable doorway pull-up bar for chin-ups and hanging exercises.', 'price': Decimal('32.00'), 'stock': 28, 'badge': 'discounted', 'descriptions': ['Fits most door frames.', 'No drilling required.', 'Multiple grip positions.', 'Supports up to 120kg.']},
    {'name': 'Exercise Bike Pedals', 'brand': 'VitaLife', 'category': 'Fitness', 'short_description': 'Under-desk cardio trainer', 'description': 'Compact under-desk pedal exerciser for low-impact cardio at home.', 'price': Decimal('45.00'), 'stock': 20, 'badge': 'new', 'descriptions': ['Low-impact desk exercise.', 'Adjustable resistance dial.', 'LCD display tracks progress.', 'Quiet and compact.']},
    {'name': 'Workout Gloves', 'brand': 'Perfectil', 'category': 'Fitness', 'short_description': 'Grip support for weight training', 'description': 'Padded workout gloves that protect hands and improve bar grip.', 'price': Decimal('16.00'), 'stock': 40, 'badge': None, 'descriptions': ['Padded palm protection.', 'Improved barbell grip.', 'Breathable mesh back.', 'Velcro wrist closure.']},
    {'name': 'Ab Roller Wheel', 'brand': 'HealthPlus', 'category': 'Fitness', 'short_description': 'Core strength ab trainer', 'description': 'Dual-wheel ab roller for core strengthening and stability training.', 'price': Decimal('18.00'), 'stock': 35, 'badge': 'discounted', 'descriptions': ['Dual-wheel stable design.', 'Strengthens core muscles.', 'Knee pad included.', 'Compact and portable.']},
    {'name': 'Medicine Ball 5kg', 'brand': 'VitaLife', 'category': 'Fitness', 'short_description': 'Dynamic functional training ball', 'description': 'Rubber medicine ball for throws, slams, and rotational exercises.', 'price': Decimal('30.00'), 'stock': 24, 'badge': 'new', 'descriptions': ['5kg rubber shell.', 'Textured grip surface.', 'For throws and slams.', 'Indoor and outdoor use.']},
    {'name': 'Balance Board', 'brand': 'Perfectil', 'category': 'Fitness', 'short_description': 'Improve stability and coordination', 'description': 'Wobble balance board for ankle stability and core coordination training.', 'price': Decimal('28.00'), 'stock': 26, 'badge': 'discounted', 'descriptions': ['360-degree wobble motion.', 'Strengthens ankles and core.', 'Non-slip top surface.', 'Supports up to 150kg.']},
    {'name': 'Running Armband', 'brand': 'HealthPlus', 'category': 'Fitness', 'short_description': 'Secure phone while running', 'description': 'Adjustable running armband with touch-screen window for smartphones.', 'price': Decimal('12.00'), 'stock': 50, 'badge': None, 'descriptions': ['Fits most smartphone sizes.', 'Touch-screen compatible window.', 'Adjustable elastic strap.', 'Reflective strip for safety.']},
    {'name': 'Stretch Strap', 'brand': 'VitaLife', 'category': 'Fitness', 'short_description': 'Deep stretching assistance', 'description': 'Multi-loop stretch strap for flexibility and physical therapy exercises.', 'price': Decimal('14.00'), 'stock': 38, 'badge': 'new', 'descriptions': ['Multiple loop grip points.', 'Improves flexibility safely.', 'Durable nylon webbing.', 'Ideal for yoga and rehab.']},
    {'name': 'Boxing Hand Wraps', 'brand': 'Perfectil', 'category': 'Fitness', 'short_description': 'Protect wrists during training', 'description': '180-inch boxing hand wraps for wrist and knuckle protection.', 'price': Decimal('10.00'), 'stock': 55, 'badge': 'discounted', 'descriptions': ['180-inch cotton wraps.', 'Protects wrists and knuckles.', 'Hook-and-loop closure.', 'Machine washable.']},
    {'name': 'Whey Protein 1kg', 'brand': 'VitaLife', 'category': 'Fitness', 'short_description': 'Post-workout muscle recovery', 'description': 'Whey protein isolate powder for muscle recovery after training.', 'price': Decimal('39.00'), 'stock': 30, 'badge': 'new', 'descriptions': ['25g protein per serving.', 'Fast-absorbing whey isolate.', 'Mixes easily in water.', 'Chocolate flavor.']},
    {'name': 'Pre-Workout Powder', 'brand': 'HealthPlus', 'category': 'Fitness', 'short_description': 'Energy boost before training', 'description': 'Pre-workout powder with caffeine and beta-alanine for energy and focus.', 'price': Decimal('34.00'), 'stock': 27, 'badge': 'discounted', 'descriptions': ['150mg caffeine per scoop.', 'Enhances workout focus.', 'Beta-alanine for endurance.', 'Fruit punch flavor.']},
    {'name': 'BCAA Powder', 'brand': 'Perfectil', 'category': 'Fitness', 'short_description': 'Branch chain amino recovery', 'description': 'BCAA powder that supports muscle recovery and reduces exercise fatigue.', 'price': Decimal('31.00'), 'stock': 29, 'badge': None, 'descriptions': ['2:1:1 BCAA ratio.', 'Supports muscle recovery.', 'Mix during or after workout.', 'Unflavored option available.']},
    {'name': 'Creatine Monohydrate', 'brand': 'VitaLife', 'category': 'Fitness', 'short_description': 'Strength and power support', 'description': 'Pure creatine monohydrate powder for strength and power output.', 'price': Decimal('27.00'), 'stock': 34, 'badge': 'new', 'descriptions': ['5g creatine per serving.', 'Micronized for mixing.', 'Supports strength gains.', 'Unflavored powder.']},
    {'name': 'Sports Water Bottle', 'brand': 'HealthPlus', 'category': 'Fitness', 'short_description': 'BPA-free 750ml bottle', 'description': 'Leak-proof sports water bottle with time markers for hydration tracking.', 'price': Decimal('11.00'), 'stock': 60, 'badge': 'discounted', 'descriptions': ['750ml BPA-free bottle.', 'Time markers for hydration.', 'Leak-proof flip lid.', 'Fits standard cup holders.']},
    {'name': 'Ginseng Energy Capsules', 'brand': 'Perfectil', 'category': 'Health care', 'short_description': 'Natural energy and vitality', 'description': 'Panax ginseng extract capsules for natural energy and mental alertness.', 'price': Decimal('23.00'), 'stock': 39, 'badge': 'new', 'descriptions': ['Standardized ginseng extract.', 'Supports natural energy.', 'Take one capsule daily.', 'No artificial stimulants.']},
    {'name': 'Spirulina Tablets', 'brand': 'VitaLife', 'category': 'Health care', 'short_description': 'Green superfood daily boost', 'description': 'Organic spirulina tablets packed with protein, iron, and antioxidants.', 'price': Decimal('20.00'), 'stock': 42, 'badge': 'discounted', 'descriptions': ['Organic spirulina source.', 'Rich in plant protein.', 'Six tablets daily.', 'Supports overall wellness.']},
    {'name': 'Chlorophyll Drops', 'brand': 'HealthPlus', 'category': 'Health care', 'short_description': 'Internal cleansing support', 'description': 'Liquid chlorophyll drops for internal cleansing and fresh breath.', 'price': Decimal('14.00'), 'stock': 46, 'badge': None, 'descriptions': ['Liquid chlorophyll concentrate.', 'Add to water daily.', 'Supports internal cleansing.', 'Mint flavor available.']},
    {'name': 'Lutein Eye Support', 'brand': 'MediCare', 'category': 'Health care', 'short_description': 'Protect vision from screen strain', 'description': 'Lutein and zeaxanthin supplement for eye health and blue light protection.', 'price': Decimal('25.00'), 'stock': 31, 'badge': 'new', 'descriptions': ['20mg lutein per capsule.', 'Supports macular health.', 'Ideal for screen users.', 'Take with meals.']},
    {'name': 'Glucosamine Chondroitin', 'brand': 'VitaLife', 'category': 'Health care', 'short_description': 'Joint flexibility support', 'description': 'Glucosamine and chondroitin combo for joint cartilage and mobility.', 'price': Decimal('30.00'), 'stock': 36, 'badge': 'discounted', 'descriptions': ['1500mg glucosamine daily.', 'Supports joint cartilage.', 'Take two tablets daily.', 'For long-term joint care.']},
    {'name': 'Evening Primrose Oil', 'brand': 'Perfectil', 'category': 'Beauty care', 'short_description': 'Hormonal balance skin support', 'description': 'Evening primrose oil softgels for hormonal balance and skin health.', 'price': Decimal('19.00'), 'stock': 33, 'badge': 'new', 'descriptions': ['Cold-pressed EPO softgels.', 'Supports hormonal balance.', 'Promotes clear skin.', 'One softgel twice daily.']},
    {'name': 'Rose Water Toner', 'brand': 'VitaLife', 'category': 'Beauty care', 'short_description': 'Hydrating natural face mist', 'description': 'Pure rose water toner and mist for refreshing and hydrating skin.', 'price': Decimal('10.00'), 'stock': 52, 'badge': 'discounted', 'descriptions': ['100% pure rose water.', 'Hydrates and refreshes skin.', 'Use as toner or mist.', 'Suitable for sensitive skin.']},
    {'name': 'Coconut Oil Hair Serum', 'brand': 'HealthPlus', 'category': 'Beauty care', 'short_description': 'Tame frizz and add shine', 'description': 'Lightweight coconut oil serum that tames frizz and adds natural shine.', 'price': Decimal('13.00'), 'stock': 44, 'badge': None, 'descriptions': ['Lightweight non-greasy formula.', 'Tames frizz and flyaways.', 'Apply to damp or dry hair.', 'Small amount goes far.']},
    {'name': 'SPF Lip Balm', 'brand': 'MediCare', 'category': 'Beauty care', 'short_description': 'Sun protection for lips', 'description': 'SPF 30 lip balm that moisturizes and protects lips from UV damage.', 'price': Decimal('7.00'), 'stock': 72, 'badge': 'new', 'descriptions': ['SPF 30 UV protection.', 'Moisturizes dry lips.', 'Water-resistant formula.', 'Apply before sun exposure.']},
    {'name': 'Micellar Cleansing Water', 'brand': 'Perfectil', 'category': 'Beauty care', 'short_description': 'Gentle no-rinse makeup remover', 'description': 'Micellar cleansing water that removes makeup without rinsing or irritation.', 'price': Decimal('15.00'), 'stock': 49, 'badge': 'discounted', 'descriptions': ['Removes makeup and impurities.', 'No rinse required.', 'Suitable for sensitive skin.', 'Use with cotton pad.']},
    {'name': 'Beard Growth Oil', 'brand': 'VitaLife', 'category': 'Beauty care', 'short_description': 'Nourish and soften beard', 'description': 'Natural beard oil with jojoba and argan to nourish and soften facial hair.', 'price': Decimal('17.00'), 'stock': 38, 'badge': 'new', 'descriptions': ['Jojoba and argan oil blend.', 'Softens and conditions beard.', 'Reduces itchiness.', 'Apply daily after shower.']},
    {'name': 'Cuticle Oil Pen', 'brand': 'HealthPlus', 'category': 'Beauty care', 'short_description': 'Nourish nails and cuticles', 'description': 'Cuticle oil pen with vitamin E for healthy nails and soft cuticles.', 'price': Decimal('8.00'), 'stock': 64, 'badge': None, 'descriptions': ['Vitamin E enriched formula.', 'Twist pen applicator.', 'Nourishes cuticles daily.', 'Travel-friendly size.']},
    {'name': 'Detox Foot Pads', 'brand': 'Perfectil', 'category': 'Beauty care', 'short_description': 'Overnight foot wellness pads', 'description': 'Natural detox foot pads worn overnight to promote relaxation and wellness.', 'price': Decimal('12.00'), 'stock': 41, 'badge': 'discounted', 'descriptions': ['Natural ingredient foot pads.', 'Apply before sleep.', 'Promotes overnight relaxation.', 'Pack of 10 pads.']},
    {'name': 'Burn Gel', 'brand': 'MediCare', 'category': 'Medicine', 'short_description': 'Cooling relief for minor burns', 'description': 'Cooling burn gel with lidocaine for minor burn and sunburn relief.', 'price': Decimal('9.00'), 'stock': 56, 'badge': 'new', 'descriptions': ['Cooling lidocaine gel.', 'Relieves minor burn pain.', 'Apply to affected area.', 'Keep in first aid kit.']},
    {'name': 'Motion Sickness Patches', 'brand': 'HealthPlus', 'category': 'Medicine', 'short_description': 'Travel nausea prevention', 'description': 'Transdermal motion sickness patches for travel and nausea prevention.', 'price': Decimal('11.00'), 'stock': 48, 'badge': 'discounted', 'descriptions': ['Apply behind ear before travel.', 'Lasts up to 72 hours.', 'Prevents motion sickness.', 'Pack of four patches.']},
    {'name': 'Hemorrhoid Cream', 'brand': 'MediCare', 'category': 'Medicine', 'short_description': 'Soothe discomfort fast', 'description': 'Topical hemorrhoid cream that reduces swelling and soothes irritation.', 'price': Decimal('10.00'), 'stock': 42, 'badge': None, 'descriptions': ['Reduces swelling and itching.', 'Fast soothing relief.', 'Apply as directed.', 'Keep refrigerated optional.']},
    {'name': 'Ear Wax Removal Drops', 'brand': 'VitaLife', 'category': 'Medicine', 'short_description': 'Softens ear wax safely', 'description': 'Ear wax removal drops that soften buildup for safe and easy cleaning.', 'price': Decimal('8.00'), 'stock': 53, 'badge': 'new', 'descriptions': ['Softens hardened ear wax.', 'Use before irrigation.', 'Gentle carbamide formula.', 'Apply twice daily.']},
    {'name': 'Athletes Foot Cream', 'brand': 'HealthPlus', 'category': 'Medicine', 'short_description': 'Treat fungal foot infections', 'description': 'Antifungal athletes foot cream for treating and preventing fungal infections.', 'price': Decimal('11.00'), 'stock': 47, 'badge': 'discounted', 'descriptions': ['Antifungal active ingredient.', 'Treats athletes foot.', 'Apply twice daily.', 'Continue one week after clearing.']},
    {'name': 'Crutch Pads', 'brand': 'MediCare', 'category': 'Medicine', 'short_description': 'Comfort padding for crutches', 'description': 'Foam crutch pads and hand grips for comfortable mobility aid use.', 'price': Decimal('13.00'), 'stock': 35, 'badge': 'new', 'descriptions': ['Foam underarm and hand pads.', 'Reduces pressure and chafing.', 'Universal fit design.', 'Easy to install.']},
    {'name': 'Pill Organizer 7-Day', 'brand': 'VitaLife', 'category': 'Medicine', 'short_description': 'Weekly medication planner', 'description': 'Seven-day pill organizer with AM/PM compartments for medication management.', 'price': Decimal('9.00'), 'stock': 68, 'badge': None, 'descriptions': ['Seven-day AM/PM compartments.', 'Snap-tight lids.', 'BPA-free plastic.', 'Compact travel size.']},
    {'name': 'Dumbbell Set 5kg Pair', 'brand': 'Perfectil', 'category': 'Fitness', 'short_description': 'Home strength training weights', 'description': 'Neoprene-coated 5kg dumbbell pair for home strength and toning workouts.', 'price': Decimal('36.00'), 'stock': 22, 'badge': 'discounted', 'descriptions': ['5kg pair neoprene dumbbells.', 'Non-slip comfortable grip.', 'Hex shape prevents rolling.', 'Ideal for toning exercises.']},
    {'name': 'Push-Up Bars', 'brand': 'HealthPlus', 'category': 'Fitness', 'short_description': 'Deep push-up range of motion', 'description': 'Ergonomic push-up bars for deeper range of motion and wrist comfort.', 'price': Decimal('15.00'), 'stock': 37, 'badge': 'new', 'descriptions': ['Ergonomic foam grips.', 'Deeper push-up range.', 'Reduces wrist strain.', 'Non-slip base pads.']},
    {'name': 'Speed Agility Ladder', 'brand': 'VitaLife', 'category': 'Fitness', 'short_description': 'Footwork and agility drills', 'description': 'Adjustable speed agility ladder for footwork drills and cardio training.', 'price': Decimal('22.00'), 'stock': 28, 'badge': 'discounted', 'descriptions': ['8-rung adjustable ladder.', 'Improves foot speed.', 'Includes carry bag.', 'Indoor and outdoor use.']},
    {'name': 'Grip Strengthener', 'brand': 'Perfectil', 'category': 'Fitness', 'short_description': 'Build hand and forearm strength', 'description': 'Adjustable hand grip strengthener for forearm and grip power training.', 'price': Decimal('13.00'), 'stock': 45, 'badge': None, 'descriptions': ['Adjustable resistance 10–40kg.', 'Strengthens grip and forearms.', 'Compact pocket size.', 'Spring-loaded mechanism.']},
    {'name': 'Yoga Block Set', 'brand': 'HealthPlus', 'category': 'Fitness', 'short_description': 'Support poses and alignment', 'description': 'High-density foam yoga block set for supported poses and alignment.', 'price': Decimal('16.00'), 'stock': 40, 'badge': 'new', 'descriptions': ['Set of two foam blocks.', 'Supports difficult poses.', 'High-density EVA foam.', 'Lightweight and durable.']},
]


class Command(BaseCommand):
    help = 'Add 70 new products with badges and short descriptions'

    def handle(self, *args, **options):
        brands = {}
        categories = {}
        created = 0
        skipped = 0

        for item in NEW_PRODUCTS:
            brands[item['brand']], _ = Brand.objects.get_or_create(name=item['brand'])
            categories[item['category']], _ = Category.objects.get_or_create(
                name=item['category'],
                defaults={'slug': item['category'].lower().replace(' ', '-')},
            )

        for item in NEW_PRODUCTS:
            if Product.objects.filter(name=item['name']).exists():
                skipped += 1
                continue

            product = Product.objects.create(
                name=item['name'],
                brand=brands[item['brand']],
                category=categories[item['category']],
                short_description=item['short_description'],
                description=item['description'],
                price=item['price'],
                stock=item['stock'],
            )
            created += 1

            if item['badge']:
                ProductBadge.objects.create(product=product, badge=item['badge'])

            for text in item['descriptions']:
                ProductDescription.objects.create(product=product, description=text)

        self.stdout.write(
            self.style.SUCCESS(
                f'Done: {created} products created, {skipped} skipped (already exist). '
                f'Total products: {Product.objects.count()}.'
            )
        )
